eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    hostname: localhost
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_url:http://192.168.0.69:9000/eureka}
  instance:
    hostname: 192.168.0.69
    prefer-ip-address: true
